name: Run tests and upload coverage

on: 
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: javascript/package-lock.json

      - name: Install dependencies
        working-directory: ./javascript
        run: npm install

      - name: Run tests
        working-directory: ./javascript
        run: JEST_JUNIT_CLASSNAME="{filepath}" NODE_OPTIONS="$NODE_OPTIONS --experimental-vm-modules" npx jest --coverage --reporters=jest-junit

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./javascript/coverage

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}          